import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import QueryProvider from "@/providers/QueryProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="flex flex-col h-screen overflow-hidden">
        <QueryProvider>
            <Header/>
            <main
                className="flex flex-col flex-1 w-full items-center justify-between sm:items-start bg-zinc-50 overflow-hidden"
            >
                {children}
            </main>
        </QueryProvider>
        </body>
        </html>
    );
}
